steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-west4-docker.pkg.dev/products-microservices-439002/image-registry/products-microservice',
        '-f',
        'dockerfile.prod',
        '--platform=linux/amd64',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-west4-docker.pkg.dev/products-microservices-439002/image-registry/products-microservice']
options:
  logging: CLOUD_LOGGING_ONLY
